/* De Mayo Bible Studies - In-browser MP4 exporter */
(function(){
'use strict';
const IOS=/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);
const FFMPEG_VERSION='0.12.15';
const CORE_VERSION='0.12.10';
const CLASS_URL=`https://cdn.jsdelivr.net/npm/@ffmpeg/ffmpeg@${FFMPEG_VERSION}/dist/esm/index.js`;
const UTIL_URL='https://cdn.jsdelivr.net/npm/@ffmpeg/util@0.12.2/dist/esm/index.js';
const CLASS_WORKER=`https://cdn.jsdelivr.net/npm/@ffmpeg/ffmpeg@${FFMPEG_VERSION}/dist/esm/worker.js`;
const CORE_BASE=`https://cdn.jsdelivr.net/npm/@ffmpeg/core@${CORE_VERSION}/dist/umd`;
let ffmpeg=null,loading=null,busy=false;
const EXPORT_WIDTH=1080;
const EXPORT_HEIGHT=1920;
const EXPORT_FPS=30;
function status(message,type='info'){
  if(typeof window.toast==='function')window.toast(message);
  const box=document.querySelector('#dmExportStatus');
  if(box){box.hidden=false;box.dataset.type=type;box.textContent=message;}
}
function wrap(ctx,text,maxWidth){const words=String(text||'').trim().split(/\s+/),lines=[];let line='';for(const word of words){const test=line?line+' '+word:word;if(line&&ctx.measureText(test).width>maxWidth){lines.push(line);line=word;}else line=test;}if(line)lines.push(line);return lines;}
function fit(ctx,text,maxWidth,maxHeight,max=58,min=24){for(let size=max;size>=min;size-=2){ctx.font=`800 ${size}px system-ui,-apple-system,sans-serif`;const lines=wrap(ctx,text,maxWidth),lh=size*1.2;if(lines.length*lh<=maxHeight)return {size,lines,lh};}ctx.font=`800 ${min}px system-ui,-apple-system,sans-serif`;return {size:min,lines:wrap(ctx,text,maxWidth),lh:min*1.2};}
function snapshotScene(){const reel=document.querySelector('.dm-reel-canvas');if(!reel)return null;const style=getComputedStyle(reel);return {kicker:reel.querySelector('.dm-reel-kicker')?.textContent||'BIBLE ENCOURAGEMENT',message:reel.querySelector('.dm-reel-message')?.textContent||'',ref:reel.querySelector('.dm-reel-reference')?.textContent||'',r1:style.getPropertyValue('--r1').trim()||'#092846',r2:style.getPropertyValue('--r2').trim()||'#2f6b88',accent:style.getPropertyValue('--accent').trim()||'#f2c96d'};}
async function collectScenes(){const scenes=[];const next=document.querySelector('#dmNext');const count=document.querySelector('#dmSceneCount')?.textContent||'';const match=count.match(/of\s+(\d+)/i),total=Math.max(1,Math.min(6,Number(match?.[1]||3)));for(let i=0;i<total;i++){const scene=snapshotScene();if(scene)scenes.push(scene);if(i<total-1&&next){next.click();await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));}}if(next){next.click();await new Promise(r=>requestAnimationFrame(r));}return scenes;}
function drawScene(ctx,scene,w,h,progress){const g=ctx.createLinearGradient(0,0,w,h);g.addColorStop(0,scene.r1);g.addColorStop(1,scene.r2);ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.globalAlpha=.12;ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(w*.2,h*.23,w*.18,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(w*.79,h*.62,w*.25,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;ctx.textAlign='center';ctx.fillStyle='rgba(255,255,255,.82)';ctx.font=`700 ${Math.round(w*.023)}px system-ui,-apple-system,sans-serif`;ctx.fillText('BIBLE REEL  •  DE MAYO BIBLE STUDIES',w/2,h*.125);ctx.fillStyle=scene.accent;ctx.font=`800 ${Math.round(w*.032)}px system-ui,-apple-system,sans-serif`;ctx.fillText(scene.kicker.toUpperCase(),w/2,h*.19);const fitted=fit(ctx,scene.message,w*.74,h*.34,Math.round(w*.09),Math.round(w*.045));ctx.fillStyle='#fff';ctx.font=`800 ${fitted.size}px system-ui,-apple-system,sans-serif`;let y=h*.40-(fitted.lines.length*fitted.lh)/2+fitted.lh/2;for(const line of fitted.lines){ctx.fillText(line,w/2,y);y+=fitted.lh;}if(scene.ref){ctx.fillStyle=scene.accent;ctx.font=`800 ${Math.round(w*.047)}px system-ui,-apple-system,sans-serif`;ctx.fillText(scene.ref,w/2,h*.60);}ctx.fillStyle='#fff';ctx.font=`800 ${Math.round(w*.041)}px system-ui,-apple-system,sans-serif`;ctx.fillText('✝  De Mayo Bible Studies',w/2,h*.685);ctx.font=`500 ${Math.round(w*.025)}px system-ui,-apple-system,sans-serif`;ctx.fillText('Grow in faith · Walk in truth',w/2,h*.715);ctx.fillStyle='rgba(255,255,255,.25)';ctx.fillRect(w*.10,h*.755,w*.80,8);ctx.fillStyle=scene.accent;ctx.fillRect(w*.10,h*.755,w*.80*Math.max(0,Math.min(1,progress)),8);}
async function makeWebm(scenes,duration){if(!window.MediaRecorder||!HTMLCanvasElement.prototype.captureStream)throw new Error('Browser video recording is not supported');const w=EXPORT_WIDTH,h=EXPORT_HEIGHT,fps=EXPORT_FPS;const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d',{alpha:false,desynchronized:true});const stream=canvas.captureStream(fps);const mime=['video/webm;codecs=vp8','video/webm'].find(x=>MediaRecorder.isTypeSupported(x))||'';const options={videoBitsPerSecond:IOS?5000000:8000000};if(mime)options.mimeType=mime;const recorder=new MediaRecorder(stream,options);const chunks=[];recorder.ondataavailable=e=>e.data.size&&chunks.push(e.data);const done=new Promise(resolve=>recorder.onstop=resolve);recorder.start(500);const total=Math.max(9,Math.min(30,duration))*1000,start=performance.now();await new Promise(resolve=>{function frame(now){const p=Math.min(1,(now-start)/total),sceneIndex=Math.min(scenes.length-1,Math.floor(p*scenes.length)),sceneProgress=(p*scenes.length)-sceneIndex;drawScene(ctx,scenes[sceneIndex]||scenes[0],w,h,sceneProgress);status(`Preparing 1080p video ${Math.round(p*45)}%…`);if(p<1)requestAnimationFrame(frame);else resolve();}requestAnimationFrame(frame);});recorder.stop();await done;return new Blob(chunks,{type:mime||'video/webm'});}
async function loadFfmpeg(){if(ffmpeg)return ffmpeg;if(loading)return loading;loading=(async()=>{status('Loading free MP4 engine for the first time…');const [{FFmpeg},{toBlobURL}]=await Promise.all([import(CLASS_URL),import(UTIL_URL)]);const instance=new FFmpeg();instance.on('progress',({progress})=>status(`Creating MP4 ${45+Math.round(Math.max(0,Math.min(1,progress))*50)}%…`));await instance.load({classWorkerURL:await toBlobURL(CLASS_WORKER,'text/javascript'),coreURL:await toBlobURL(`${CORE_BASE}/ffmpeg-core.js`,'text/javascript'),wasmURL:await toBlobURL(`${CORE_BASE}/ffmpeg-core.wasm`,'application/wasm')});ffmpeg=instance;return instance;})();try{return await loading;}finally{loading=null;}}
async function shareMp4(blob){const name=`de-mayo-bible-reel-${new Date().toISOString().slice(0,10)}.mp4`,file=new File([blob],name,{type:'video/mp4'}),url=URL.createObjectURL(blob);if(navigator.share&&navigator.canShare&&navigator.canShare({files:[file]})){await navigator.share({files:[file],title:'De Mayo Bible Reel',text:'Created with De Mayo Bible Studies'});status('MP4 ready. Choose Save Video or Facebook in the Share Sheet.','success');return;}const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();status('MP4 saved to Downloads.','success');}
async function createBrowserMp4(){if(busy)return;busy=true;const btn=document.querySelector('#dmBrowserMp4');if(btn)btn.disabled=true;try{const scenes=await collectScenes();if(!scenes.length)throw new Error('Reel preview is not ready');const duration=Number(document.querySelector('#dmDuration')?.value||15);const webm=await makeWebm(scenes,duration);const engine=await loadFfmpeg();await engine.writeFile('input.webm',new Uint8Array(await webm.arrayBuffer()));const code=await engine.exec(['-i','input.webm','-c:v','libx264','-preset','veryfast','-crf','20','-pix_fmt','yuv420p','-r',String(EXPORT_FPS),'-movflags','+faststart','output.mp4']);if(code!==0)throw new Error('MP4 conversion failed');const data=await engine.readFile('output.mp4');const blob=new Blob([data.buffer],{type:'video/mp4'});if(!blob.size)throw new Error('Empty MP4 file');await shareMp4(blob);try{await engine.deleteFile('input.webm');await engine.deleteFile('output.mp4');}catch{}}
catch(error){console.error(error);status('This device could not create the MP4 in-browser. Try a shorter 15-second Reel or use a Mac/PC.','error');}
finally{busy=false;if(btn){btn.disabled=false;btn.textContent=IOS?'🎬 Create MP4 & Save to Photos':'🎬 Create MP4';}}}
function install(){const actions=document.querySelector('.dm-reel-actions');if(!actions||document.querySelector('#dmBrowserMp4'))return;document.querySelectorAll('#dmOpenMp4,#dmSaveFinishedVideo,#dmCreateMp4').forEach(el=>el.style.display='none');const old=document.querySelector('#dmSaveVideo');if(old)old.style.display='none';const button=document.createElement('button');button.id='dmBrowserMp4';button.className='primary';button.textContent=IOS?'🎬 Create MP4 & Save to Photos':'🎬 Create MP4';button.addEventListener('click',createBrowserMp4);actions.appendChild(button);const guide=document.createElement('section');guide.className='card dm-browser-mp4-guide';guide.innerHTML=`<h3>One-button MP4 export</h3><p>Tap <b>${IOS?'Create MP4 & Save to Photos':'Create MP4'}</b>. The first use downloads the free video engine, then the Reel is created on this device. ${IOS?'When the Share Sheet opens, choose <b>Save Video</b> or <b>Facebook</b>.':'The MP4 will save to Downloads.'}</p><p class="small-note">For best results on phones, use a 15-second Reel and keep this page open while rendering.</p>`;actions.insertAdjacentElement('afterend',guide);}
window.addEventListener('load',install);window.addEventListener('hashchange',()=>setTimeout(install,0));document.addEventListener('dm-reel-studio-ready',install);
})();
