/* De Mayo Bible Studies - iPhone Reel Save/Share Enhancement */
(function(){
'use strict';
const IOS=/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);
const WORKFLOW_URL='https://github.com/romerdemayo/de-mayo-bible-study-dev/actions/workflows/render-bible-reel-v2.yml';
let cachedFile=null;
let cacheKey='';
function wrap(ctx,text,maxWidth){const words=String(text||'').trim().split(/\s+/),lines=[],lineParts=[];let line='';for(const word of words){const test=line?line+' '+word:word;if(line&&ctx.measureText(test).width>maxWidth){lines.push(line);line=word;}else line=test;}if(line)lines.push(line);return lines;}
function fit(ctx,text,maxWidth,maxHeight,max=90,min=38){for(let size=max;size>=min;size-=2){ctx.font=`800 ${size}px system-ui,-apple-system,sans-serif`;const lines=wrap(ctx,text,maxWidth),lh=size*1.2;if(lines.length*lh<=maxHeight)return {size,lines,lh};}ctx.font=`800 ${min}px system-ui,-apple-system,sans-serif`;return {size:min,lines:wrap(ctx,text,maxWidth),lh:min*1.2};}
async function buildFile(){const reel=document.querySelector('.dm-reel-canvas');if(!reel)return null;const kicker=reel.querySelector('.dm-reel-kicker')?.textContent||'BIBLE ENCOURAGEMENT';const message=reel.querySelector('.dm-reel-message')?.textContent||'';const ref=reel.querySelector('.dm-reel-reference')?.textContent||'';const style=getComputedStyle(reel),r1=style.getPropertyValue('--r1').trim()||'#092846',r2=style.getPropertyValue('--r2').trim()||'#2f6b88',accent=style.getPropertyValue('--accent').trim()||'#f2c96d';const key=[kicker,message,ref,r1,r2,accent].join('|');if(key===cacheKey&&cachedFile)return cachedFile;const c=document.createElement('canvas');c.width=1080;c.height=1920;const ctx=c.getContext('2d');const g=ctx.createLinearGradient(0,0,1080,1920);g.addColorStop(0,r1);g.addColorStop(1,r2);ctx.fillStyle=g;ctx.fillRect(0,0,1080,1920);ctx.globalAlpha=.12;ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(220,430,190,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(840,1320,280,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;ctx.textAlign='center';ctx.fillStyle=accent;ctx.font='800 34px system-ui,-apple-system,sans-serif';ctx.fillText(kicker.toUpperCase(),540,300);const fitted=fit(ctx,message,820,850);ctx.fillStyle='#fff';ctx.font=`800 ${fitted.size}px system-ui,-apple-system,sans-serif`;let y=690-(fitted.lines.length*fitted.lh)/2;for(const line of fitted.lines){ctx.fillText(line,540,y);y+=fitted.lh;}if(ref){ctx.fillStyle=accent;ctx.font='800 44px system-ui,-apple-system,sans-serif';ctx.fillText(ref,540,1260);}ctx.fillStyle='#fff';ctx.font='800 40px system-ui,-apple-system,sans-serif';ctx.fillText('✝  De Mayo Bible Studies',540,1650);ctx.font='500 25px system-ui,-apple-system,sans-serif';ctx.fillText('Grow in faith · Walk in truth',540,1705);const blob=await new Promise(resolve=>c.toBlob(resolve,'image/png',.95));if(!blob)return null;cachedFile=new File([blob],`de-mayo-bible-reel-${new Date().toISOString().slice(0,10)}.png`,{type:'image/png'});cacheKey=key;return cachedFile;}
function status(msg,type='success'){if(typeof toast==='function')toast(msg);const box=document.querySelector('#dmExportStatus');if(box){box.hidden=false;box.dataset.type=type;box.textContent=msg;}}
async function sharePicture(){const file=await buildFile();if(!file)return status('The Reel preview is not ready yet.','error');try{if(navigator.share&&navigator.canShare&&navigator.canShare({files:[file]})){await navigator.share({files:[file],title:'De Mayo Bible Reel',text:'Created with De Mayo Bible Studies'});status('Share menu opened. Choose Facebook, Save Image, or Save to Files.');return;}const url=URL.createObjectURL(file),a=document.createElement('a');a.href=url;a.download=file.name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),4000);status('Picture saved to Downloads.');}catch(err){if(err&&err.name==='AbortError')return;console.error(err);status('Unable to open the Share menu. Try Save cover instead.','error');}}
async function shareFinishedVideo(file){if(!file)return;const isMp4=file.type==='video/mp4'||/\.mp4$/i.test(file.name);if(!isMp4)return status('Please choose the finished .mp4 Reel file. WebM is not supported by iPhone Photos.','error');try{if(navigator.share&&navigator.canShare&&navigator.canShare({files:[file]})){await navigator.share({files:[file],title:'De Mayo Bible Reel',text:'Created with De Mayo Bible Studies'});status('iPhone Share Sheet opened. Choose Save Video to put it in Photos, or Facebook to post it.');return;}const url=URL.createObjectURL(file),a=document.createElement('a');a.href=url;a.download=file.name||'de-mayo-bible-reel.mp4';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),5000);status('MP4 downloaded. Open it in Files, tap Share, then choose Save Video.');}catch(err){if(err&&err.name==='AbortError')return;console.error(err);status('Unable to share this MP4. Open it from Files and use the iPhone Share button.','error');}}
function openMp4Workflow(){status('Opening the MP4 renderer. Run the workflow, then download the finished MP4 artifact.');window.open(WORKFLOW_URL,'_blank','noopener');}
function replaceIphoneWebmAction(){if(!IOS)return;const webm=document.querySelector('#dmSaveVideo');if(webm&&!webm.dataset.iphoneMp4){webm.dataset.iphoneMp4='true';webm.textContent='🎬 Create MP4 for iPhone';webm.classList.add('primary');webm.onclick=openMp4Workflow;webm.setAttribute('aria-label','Create iPhone-compatible MP4 Reel');}const oldMp4=document.querySelector('#dmCreateMp4');if(oldMp4)oldMp4.hidden=true;const help=document.querySelector('#dmSaveHelp');if(help)help.innerHTML='<b>iPhone uses MP4 only.</b> WebM has been disabled because it cannot open in Photos. Create the MP4, then use Save Finished Video to Photos.';}
function addControls(){const actions=document.querySelector('.dm-reel-actions');if(!actions)return;replaceIphoneWebmAction();if(document.querySelector('#dmIphoneShare'))return;const share=document.createElement('button');share.id='dmIphoneShare';share.className='primary';share.textContent=IOS?'📱 Save/Share Picture':'📤 Share Reel picture';share.addEventListener('click',sharePicture);actions.appendChild(share);const mp4=document.createElement('button');mp4.id='dmOpenMp4';mp4.textContent='🎬 Create Finished MP4';mp4.addEventListener('click',openMp4Workflow);actions.appendChild(mp4);const picker=document.createElement('input');picker.id='dmFinishedVideoPicker';picker.type='file';picker.accept='video/mp4,.mp4';picker.hidden=true;picker.addEventListener('change',()=>{const file=picker.files&&picker.files[0];shareFinishedVideo(file);picker.value='';});actions.appendChild(picker);const saveVideo=document.createElement('button');saveVideo.id='dmSaveFinishedVideo';saveVideo.className='primary';saveVideo.textContent=IOS?'📲 Save Finished Video to Photos':'📲 Share Finished MP4';saveVideo.addEventListener('click',()=>picker.click());actions.appendChild(saveVideo);const guide=document.createElement('section');guide.className='card dm-iphone-guide';guide.innerHTML=`<h3>Save the finished MP4 to iPhone Photos</h3><ol><li>Tap <b>Create MP4 for iPhone</b>.</li><li>Run the GitHub workflow and download the <b>de-mayo-bible-reel-mp4</b> artifact.</li><li>Unzip it in the iPhone <b>Files</b> app.</li><li>Return here and tap <b>Save Finished Video to Photos</b>.</li><li>Select the MP4, then choose <b>Save Video</b> or <b>Facebook</b> in the Share Sheet.</li></ol><p><b>Important:</b> WebM is disabled on iPhone because iOS Photos cannot open it. Use MP4 only.</p>`;actions.insertAdjacentElement('afterend',guide);buildFile();}
const observer=new MutationObserver(()=>{addControls();replaceIphoneWebmAction();if(document.querySelector('.dm-reel-canvas'))buildFile();});observer.observe(document.documentElement,{childList:true,subtree:true,characterData:true});window.addEventListener('load',addControls);
})();